<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $config Require keys "root", "iiifResourceUri" and "configUri".
 * @var string $version Optional
 *
 * @link https://github.com/UniversalViewer/universalviewer/wiki/V3
 */

if (isset($version) && $version === '2'):
?>

<div id="<?= $config['id'] ?>" class="uv universal-viewer viewer <?= $config['class'] ?? '' ?>" data-config="<?= $config['configUri'] ?>" data-uri="<?= $config['iiifResourceUri'] ?>" data-locale="<?= $config['locale'] ?>" style="<?= $config['style'] ?>"></div>

<?php else:

$config['id'] = $config['id'] ?? 'uv';
$configJson = json_encode($config, 448);
$script = <<<JS
if (typeof uv === 'undefined') {
    var uv = [];
}
uv.push($configJson);
JS;

$this->headScript()
    ->appendFile($this->assetUrl('js/universal-viewer.js', 'UniversalViewer'), 'text/javascript', ['defer' => 'defer'])
    ->appendScript($script);
?>

<div id="<?= $config['id'] ?>" class="universal-viewer viewer"></div>

<?php endif;
