<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $config Require keys "root", "iiifResourceUri" and "configUri".
 *
 * @link https://github.com/UniversalViewer/universalviewer/wiki/V3
 */

$config['id'] = isset($config['id']) ? $config['id'] : 'uv';
$configJson = json_encode($config, 448);
$script = <<<JS
if (typeof uv === 'undefined') {
    var uv = [];
}
uv.push($configJson);
JS;

$this->headScript()
    ->appendFile($this->assetUrl('js/universal-viewer.js', 'UniversalViewer'), 'text/javascript', ['defer' => 'defer'])
    ->appendScript($script);
?>

<div id="<?= $config['id'] ?>" class="universal-viewer viewer"></div>
