<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $config Require keys "root", "iiifResourceUri" and "configUri"
 * @var string $version 2, 3 or 4 (default)
 *
 * @link https://github.com/UniversalViewer/universalviewer/wiki/V3
 *
 * This file is kept for old themes.
 * Use view/common/universal-viewer.phtml instead.
 */

include dirname(__DIR__) . '/universal-viewer.phtml';
