<fieldset id="fieldset-iiifserver-manifest">
    <legend><?php echo $t->translate('IIIF Manifests'); ?></legend>
    <p class="explanation">
        <?php echo $t->translate('The module uses an url to fetch data and medias to display.'); ?>
        <?php if ($iiifServerIsActive): ?>
        <?php echo $t->translate('The IIIF Server is active, so when no url is set, the viewer will use the standard routes.'); ?>
        <?php else: ?>
        <?php echo $t->translate('The IIIF Server is not active, so when no url is set, the viewer won’t be displayed.'); ?>
        <?php endif; ?>
    </p>
    <div class="field">
        <?php
        $select = new Zend\Form\Element\Select('universalviewer_manifest_property');
        $select
            ->setLabel($t->translate('Manifest Property'))
            ->setAttribute('id', 'universalviewer_manifest_property')
            ->setValue($settings->get('universalviewer_manifest_property'))
            ->setEmptyOption($t->translate('Select a property...'))
            ->setValueOptions($properties);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($select); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('The property supplying the manifest URL for the viewer, for example "dcterms:hasFormat".'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formSelect($select); ?>
        </div>
    </div>
</fieldset>
<fieldset id="fieldset-universalviewer-embed">
    <legend><?php echo $t->translate('Integration of the viewer'); ?></legend>
    <p class="explanation">
        <?php echo $t->translate('If checked, the viewer will be automatically appended to the item sets or items pages.'); ?>
        <?php echo $t->translate('Else, the viewer can be added via the helper in the theme or the shortcode in any page.'); ?>
    </p>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_set_show');
            $checkbox->setLabel($t->translate('Append to "Item set show"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_set_show');
            $checkbox->setValue($settings->get('universalviewer_append_item_set_show'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_show');
            $checkbox->setLabel($t->translate('Append to "Item show"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_show');
            $checkbox->setValue($settings->get('universalviewer_append_item_show'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <p class="explanation">
        <?php if (!$iiifServerIsActive): ?>
        <?php echo $t->translate('The IIIF Server is not active, so the Universal Viewer can’t display lists.'); ?>
        <?php endif; ?>
    </p>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_set_browse');
            $checkbox->setLabel($t->translate('Append to "Item set browse"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_set_browse');
            $checkbox->setValue($settings->get('universalviewer_append_item_set_browse'));
            $checkbox->setAttribute('disabled', !$iiifServerIsActive);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_browse');
            $checkbox->setLabel($t->translate('Append to "Item browse"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_browse');
            $checkbox->setValue($settings->get('universalviewer_append_item_browse'));
            $checkbox->setAttribute('disabled', !$iiifServerIsActive);
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <p class="explanation">
        <?php echo $t->translate('These values allows to parameter the integration of the viewer in Omeka pages.'); ?>
        <?php echo $t->translate('The viewer itself can be configured via the file "config.json" and the helper.'); ?>
    </p>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_class');
            $text->setLabel($t->translate('Class of main div'));
            $text->setAttribute('id', 'universalviewer_class');
            $text->setValue($settings->get('universalviewer_class'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('Class to add to the main div.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_style');
            $text->setLabel($t->translate('Inline style'));
            $text->setAttribute('id', 'universalviewer_style');
            $text->setValue($settings->get('universalviewer_style'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, this style will be added to the main div of the Universal Viewer.'); ?>
                    <?php echo $t->translate('The height may be required.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_locale');
            $text->setLabel($t->translate('Locales of the viewer'));
            $text->setAttribute('id', 'universalviewer_locale');
            $text->setValue($settings->get('universalviewer_locale'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
</fieldset>
