<fieldset id="fieldset-universalviewer-embed">
    <legend><?php echo $t->translate('Integration of the viewer'); ?></legend>
    <p class="explanation">
        <?php echo $t->translate('If checked, the viewer will be automatically appended to the item sets or items pages.'); ?>
        <?php echo $t->translate('Else, the viewer can be added via the helper in the theme or the shortcode in any page.'); ?>
    </p>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_set_show');
            $checkbox->setLabel($t->translate('Append to "Item set show"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_set_show');
            $checkbox->setValue($settings->get('universalviewer_append_item_set_show'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_show');
            $checkbox->setLabel($t->translate('Append to "Item show"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_show');
            $checkbox->setValue($settings->get('universalviewer_append_item_show'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_set_browse');
            $checkbox->setLabel($t->translate('Append to "Item set browse"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_set_browse');
            $checkbox->setValue($settings->get('universalviewer_append_item_set_browse'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $checkbox = new Zend\Form\Element\Checkbox('universalviewer_append_item_browse');
            $checkbox->setLabel($t->translate('Append to "Item browse"'));
            $checkbox->setAttribute('id', 'universalviewer_append_item_browse');
            $checkbox->setValue($settings->get('universalviewer_append_item_browse'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($checkbox); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formCheckbox($checkbox); ?>
        </div>
    </div>
    <p class="explanation">
        <?php echo $t->translate('These values allows to parameter the integration of the viewer in Omeka pages.'); ?>
        <?php echo $t->translate('The viewer itself can be configured via the file "config.json" and the helper.'); ?>
    </p>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_class');
            $text->setLabel($t->translate('Class of main div'));
            $text->setAttribute('id', 'universalviewer_class');
            $text->setValue($settings->get('universalviewer_class'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('Class to add to the main div.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_style');
            $text->setLabel($t->translate('Inline style'));
            $text->setAttribute('id', 'universalviewer_style');
            $text->setValue($settings->get('universalviewer_style'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
            <a class="expand" href="#"></a>
            <div class="collapsible">
                <div class="field-description">
                    <?php echo $t->translate('If any, this style will be added to the main div of the Universal Viewer.'); ?>
                    <?php echo $t->translate('The height may be required.'); ?>
                </div>
            </div>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
    <div class="field">
        <?php
            $text = new Zend\Form\Element\Text('universalviewer_locale');
            $text->setLabel($t->translate('Locales of the viewer'));
            $text->setAttribute('id', 'universalviewer_locale');
            $text->setValue($settings->get('universalviewer_locale'));
        ?>
        <div class="field-meta">
            <?php echo $this->formLabel($text); ?>
        </div>
        <div class="inputs">
            <?php echo $this->formText($text); ?>
        </div>
    </div>
</fieldset>
